baseURL = 'http://personalblog.github.io/'
languageCode = 'en-us'
title = 'KG Blog'

theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/kssgarcia"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
